import 'events_model.dart';

final List<Event> events = [

  //Technical

  Event(
    id: "tech1",
    category: "technical",
    name: "Cad Catalyst",
    image: "assets/event_poster/tech1.png",
    description: "Unleash your creativity and your skills in our cutting-edge CAD competition. Design innovative 3D models using advanced computer-aided design software whether it's engineering marvels or futuristic concepts. Think it and design it!",
    rules: "https://docs.google.com/document/d/1NMOfWv29UCNxXkPIQwV1hkZuIPrr-4l5/edit?usp=sharing&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Ayush Dutta', phone: '8972851567'),
    ],
    gform: "",
  ),
  Event(
    id: "tech2",
    category: "technical",
    name: "Hydroblast",
    image: "assets/event_poster/tech2.png",
    description: "Hydroblast is an exhilarating water rocket competition where participants apply principles of science, engineering, and creativity to design and launch rockets powered by water and compressed air. The objective is to achieve maximum altitude, flight duration, or precise target landing. This event offers a thrilling, hands-on experience that encourages innovation while exploring key concepts of aerodynamics, fluid mechanics, and propulsion in a fun and competitive environment.\nNote: Pointy Rockets will be rejected.",
    rules: "https://docs.google.com/document/d/1AkJDJC55Zac6UYsRCsgW8VlES7xJmrxa/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 100,
    gform: "",
    prizePool: {"first": 2500, "second": 1500, "third": 500},
    coordinators: [
      Coordinator(name: 'Shlok Vyas', phone: '7779017229'),
    ],
  ),
  Event(
    id: "tech3",
    category: "technical",
    name: "Rise Above",
    image: "assets/event_poster/tech3.png",
    description: "RC Plane Competition is a technical event where participants design, build, and fly radio-controlled aircraft capable of carrying a payload. The aircraft must take off smoothly, demonstrate stable flight, and remain airborne for at least 30 seconds while carrying the load. This event tests creativity, engineering skills, and the practical application of aerodynamics.",
    rules: "https://docs.google.com/document/d/1aKx0DHlXb5vVwz-R2v9807d1A4Gv-R0H/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 400,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Mehul Mehta', phone: '7973924794'),
    ],
  ),
  Event(
    id: "tech4",
    category: "technical",
    name: "Doped",
    image: "assets/event_poster/tech4.png",
    description: "An exciting event under Instruo, organized by the Department of Electronics and Telecommunication Engineering, is designed for the true fanatics of electronics. It offers a platform to explore the fascinating world of semiconductors, circuits, and logical reasoning. The event comprises two rounds: an initial quiz round featuring both technical and aptitude-based questions, followed by an advanced quiz/task round that challenges participants at placement-level difficulty. With a focus on RLC circuits, Digital Logic, and Network Theory, participants are expected to showcase both knowledge and analytical skills. Teams of up to two members can participate, with no calculators allowed to ensure fair play. Accuracy is rewarded through a strict marking scheme, and malpractice will result in disqualification.So, bias your thoughts, hold on to your electrons, and get ready to experience the “dope” world of electronics.",
    rules: "https://drive.google.com/file/d/1u5qZLwOJ5WnLlH1wlcUza5-bGBPnGyDX/view?usp=drive_link",
    minTeamSize: 1,
    maxTeamSize: 2,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Divyanand Tripathi', phone: '8305274961'),
    ],
  ),
  Event(
    id: "tech5",
    category: "technical",
    name: "TRUSSt It",
    image: "assets/event_poster/tech5.png",
    description: "Take on this hands-on engineering challenge and design sturdy bridges using popsicles and cardboard! Test your structural design skills, precision, creativity, and teamwork as you bring engineering concepts to life. Who will construct the strongest bridge and rise above the rest?\nThe objective is to construct the strongest and most efficient bridge using only the materials we provide.  Your team's creation will be loaded until it reaches its breaking point to see whose design reigns supreme.",
    rules: "https://docs.google.com/document/d/1-7sTC5_kaKiY1rnkgxp-45p7gaiDwJD7/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 3,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Harsh Gautam', phone: '9761312100'),
    ],
  ),
  Event(
    id: "tech6",
    category: "technical",
    name: "Wired In",
    image: "assets/event_poster/tech6.png",
    description: "A two-stage technical challenge designed to test your foundational electrical and electronics engineering knowledge. From theory to hands-on application, prove your mastery and rise to the top!",
    rules: "https://drive.google.com/file/d/1wuGON1Hrsf4Ljk9WcPH2IjjuHI0Fqd7y/view?usp=drive_link",
    minTeamSize: 1,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Sumit Kr. Gupta', phone: '8858031046'),
    ],
  ),
  Event(
    id: "tech7",
    category: "technical",
    name: "EOFool",
    image: "assets/event_poster/tech7.png",
    description: "Hack. Hunt. Conquer. Get ready for 48 hours of intense online hacking! Participate solo or in teams of up to 3 and dive into challenges across: Forensics, Web Vulnerabilities, Cryptography and Reverse Engineering. Puzzles Hunt hidden flags in the format EOF{...} and submit them to earn points — early solves score higher! This event is all about sharpening skills, creativity, and teamwork. Play fair, document your solutions, and enjoy the thrill of the hunt!",
    rules: "https://drive.google.com/file/d/1mTKvo2ViCdoLXdmRxomJQqDATAhjPu5Z/view?usp=drive_link",
    minTeamSize: 1,
    maxTeamSize: 3,
    fee: 200,
    gform: "https://forms.gle/jy498paNWitDbejw6",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Soham Haldar', phone: '8910827714'),
    ],
  ),
  Event(
    id: "tech8",
    category: "technical",
    name: "ODE to Code",
    image: "assets/event_poster/tech8.png",
    description: "Join the ultimate coding battle that tests your skills, speed, and problem-solving prowess. Work with your team to tackle challenging problems, think fast, and code smarter. Sharpen your logic, stay calm under pressure, and let your code speak for you!\nJoin the IIEST Shibpur Group on Codeforces as Participant: \nhttps://codeforces.com/group/Bm2GlT8MYu\nNote: Time and date will be shared soon on the Codeforces Group (IIEST Shibpur) blog.",
    rules: "https://docs.google.com/document/d/1J4kJDK4gHtcHEI1ABlozsHu7St2iWOL6/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 3000, "third": 2000},
    coordinators: [
      Coordinator(name: 'Abhinav Verma', phone: '9151740565'),
    ],
  ),
  Event(
    id: "tech9",
    category: "technical",
    name: "Hardness Hustle",
    image: "assets/event_poster/tech9.png",
    description: "Hardness Hustle is where science meets steel and knowledge meets fire! In round one, test your fundamentals in an intense quiz covering the depths of material science and heat treatment. The top scorers advance to round two — a real lab challenge where you heat, treat, and harden mild steel to perfection. Compete for the highest Brinell Hardness Number while following safety, precision, and technique. This is engineering in its purest form — tough, technical, and totally thrilling!",
    rules: "https://docs.google.com/document/d/1Hjqz8Hzpt0f6TXmGRRwtd3_2qQVz7zaX/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Himanshu Kumar', phone: '7413920624'),
    ],
  ),

  // GENERAL

  Event(
    id: "gen1",
    category: "general",
    name: "Narrimate",
    image: "assets/event_poster/gen1.png",
    description: "Unleash your imagination and let technology bring your story to life! Join this 2–3 min short animated story-making competition where creativity meets AI. Write your own script. Animate it using AI or any other tool. Create magic in motion! Judgement Criteria: Script quality, Animation style, Uniqueness of concept. So, storytellers and innovators — it’s your time to narrate, animate, and NARRIMATE!",
    rules: "https://drive.google.com/file/d/1eqE2f8LDadkLW6qnpgXSf6ubfAMY9Qah/view?usp=drive_link",
    minTeamSize: 1,
    maxTeamSize: 3,
    fee: 200,
    gform: "https://docs.google.com/forms/d/e/1FAIpQLSck4EjnsbPvWJP4DWoAEzYvXE4LjAoNksQxl-zcPBqimXRnAw/viewform?usp=header",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Dhruv Kumar', phone: '7783036251'),
    ],
  ),
  Event(
    id: "gen2",
    category: "general",
    name: "Craft N Cut",
    image: "assets/event_poster/gen2.png",
    description: "Edit. Create. Amaze. Step into this offline editing showdown where creativity meets the clock! Using provided footage, participants will cut, mix, and style their way to craft a stunning short film or video edit — all on-site. Judgement will be based on editing skills, creativity, and originality — the true test of storytelling through visuals!",
    rules: "https://drive.google.com/file/d/1HWf64s1DWQ9vgHOKRNHZ3L-G-ypK8gnx/view?usp=sharing",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Santanu Mahata', phone: '9932734493'),
    ],
  ),
  Event(
    id: "gen3",
    category: "general",
    name: "Chitrakatha",
    image: "assets/event_poster/gen3.png",
    description: "Capture. Arrange. Narrate. Bring your creativity and storytelling skills to life in this unique photography-based competition! Arrange a sequence of photographs to tell a compelling story — without words, relying solely on imagery, perspective, and sequence to convey emotions, themes, and messages. Why Participate? Showcase your photography & storytelling talent, Develop narrative skills through visual expressionand to enjoy a creative, fun, and competitive platform. Contribute to the artistic vibrance of Instruo",
    rules: "https://docs.google.com/document/d/1QbOBHN0GS0pQZ-Kl8LUktvuf4bNXaV3J/edit?usp=sharing&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "https://docs.google.com/forms/d/e/1FAIpQLSflOigCjGahmxU-S93yXHdN6-tXSwWCwLZ5rFRJfUmOzL389Q/viewform?usp=header",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Nikhil Kumar', phone: '7858010472'),
    ],
  ),
  Event(
    id: "gen4",
    category: "general",
    name: "Vicharagni",
    image: "assets/event_poster/gen4.png",
    description: "Vicharagni is where intellect meets eloquence and ideas turn into powerful debates! Blending the charm of Oxford-style discussions with the intensity of British Parliamentary debating, this event challenges you to think critically, argue logically, and speak fearlessly. Topics range from technical and scientific issues to social and ethical dilemmas, ensuring no two rounds feel the same. It’s not just about winning — it’s about refining your reasoning, composure, and conviction. Step into the arena, defend your perspective, and let your words set the stage ablaze!",
    rules: "https://docs.google.com/document/d/1cJvH15il9kA6DN_hGcQI6KRD09IKK6tC/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 3,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2400, "third": 1600},
    coordinators: [
      Coordinator(name: 'Anurag Singh', phone: '8169687574'),
    ],
  ),
  Event(
    id: "gen5",
    category: "general",
    name: "Founder's Goal",
    image: "assets/event_poster/gen5.png",
    description: "Ever wondered what it feels like to sit in the founder’s chair? Here’s your chance to step into real startup scenarios, face tough turning points, and make the bold decisions that could change everything. It’s not about what you know — it’s about how you think. Be sharp. Be daring. Be strategic. Because one decision can define the future.",
    rules: "https://drive.google.com/file/d/14Cf6zvaQdKbCt1k_6m4PRjrlj4JHG-j0/view?usp=drive_link",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 5000, "second": 3000, "third": 2000},
    coordinators: [
      Coordinator(name: 'Yash Mahajan', phone: '9503672254'),
      Coordinator(name: 'Arnav Aarit', phone: '9060227813'),
    ],
  ),
  Event(
    id: "gen6",
    category: "general",
    name: "Ignite",
    image: "assets/event_poster/gen6.png",
    description: "Fuel your mind. Spark your ideas. A two-round challenge designed to test your analytical brilliance and presentation power! Round 1: Analyze a real-world case study and propose innovative written solutions. Round 2: The shortlisted minds step up to present their ideas through a powerful PowerPoint presentation. Show us how you think, create, and communicate — because every great idea starts with a spark!",
    rules: "https://docs.google.com/document/d/177W53fdttossRPcz0lnI2dZ7zfLHAVPu/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 3,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Chitranjan Kumar', phone: '7413936203'),
    ],
  ),
  Event(
    id: "gen7",
    category: "general",
    name: "Battle of Bards",
    image: "assets/event_poster/gen7.png",
    description: " Where wit meets words and speed meets smarts! Get ready for a fast-paced, multi-round challenge filled with quick prompts, clever puzzles, and fun mini-games. It’s all about being spontaneous, thinking smart, and playing with words while cracking technical clues on the go!",
    rules: "https://docs.google.com/document/d/1x5no3JG5GVs9EyE1J3edxOvEQDHxyiy3/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 2750, "second": 1500, "third": 750},
    coordinators: [
      Coordinator(name: 'Diya Ghosh', phone: '9531614180'),
    ],
  ),
  Event(
    id: "gen8",
    category: "general",
    name: "Mathemania",
    image: "assets/event_poster/gen8.png",
    description: "Calculate. Visualize. Amaze. A quiz competition that tests both analytical and creative problem-solving skills!\n\nRound 1: Solve questions on pure mathematics, quantitative aptitude, and logical reasoning.\n\nRound 2: Recreate a given image using mathematical equations on Desmos, showcasing your mathematical creativity and visualization skills.\n\nOnly the sharpest minds and most creative problem-solvers will rise to the challenge!",
    rules: "https://drive.google.com/file/d/1P81tf9iqeDhyMaklBFFVz2cj-wsJXR2V/view?usp=drive_link",
    minTeamSize: 1,
    maxTeamSize: 2,
    fee: 200,
    gform: "",
    prizePool: {"first": 2500, "second": 1500, "third": 1000},
    coordinators: [
      Coordinator(name: 'Arijit Malakar', phone: '7362991063'),
      Coordinator(name: 'Achintya Sandilya', phone: '6299246335'),
    ],
  ),
  Event(
    id: "gen9",
    category: "general",
    name: "MayDay Mystery",
    image: "assets/event_poster/gen9.png",
    description: "Get ready for the ultimate treasure hunt adventure where your wits, instincts, and teamwork are put to the test! Solve riddles, crack puzzles, and chase clues that lead you across hidden locations, each one more intriguing than the last. Every clue unravels a story, every decision brings you closer to victory, and every step is a rush of adrenaline. It’s not just about finding the treasure — it’s about discovering how far your logic, coordination, and curiosity can take you! Gather your squad, trust your instincts, and let adventure be your guide",
    rules: "https://docs.google.com/document/d/1gjRXHdtFh2N_5dU15wt-1_94nJHhr87X/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Anamika Singh', phone: '9932692869'),
    ],
  ),
  Event(
    id: "gen10",
    category: "general",
    name: "War of Titans",
    image: "assets/event_poster/gen10.png",
    description: "War of Titans is a cerebral battleground that tests your reasoning, awareness, and intellect through rounds of aptitude and analysis. Round one measures your problem-solving and logical thinking, while round two challenges your real-world knowledge and current affairs awareness. It’s a fusion of intelligence, teamwork, and adaptability — a place where sharp minds rise and quick thinkers reign. Enter this war of wits and prove that your mind is mightier than the sword!",
    rules: "https://docs.google.com/document/d/1M1BULnxH11kWZfa5YexWIJVvAWBfp7Qv/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 2,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Harsh Agrawal', phone: '7488484122'),
    ],
  ),
  Event(
    id: "gen11",
    category: "general",
    name: "Junkyard",
    image: "assets/event_poster/gen11.png",
    description: " Think. Build. Conquer. Compete in teams of 2–3 in this two-round challenge designed to test your mind and hands! Round 1: Solve an aptitude test with quantitative, logical, and verbal questions within 1 hour. Round 2: Use scrap materials to build a working model or structure in 2 hours. This event tests your analytical skills, creativity, and teamwork — only the smartest and most inventive will prevail",
    rules: "https://docs.google.com/document/d/1u__oqOBEC2FffxYCWCtC0g2FMRAsbzz6/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 3,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Anish Mansuri', phone: '8340243520'),
    ],
  ),
  Event(
    id: "gen12",
    category: "general",
    name: "SpeedCubing",
    image: "assets/event_poster/gen12.png",
    description: "Ready, set, twist! SOCIT brings you the ultimate Speedcubing Challenge, where quick thinking meets lightning-fast fingers! Solve the classic 3×3 Rubik’s Cube in record time and prove your mastery over color, logic, and pure focus. Every second counts as you twist, turn, and snap your way toward perfection — can you beat the clock before anyone else? Whether you’re a casual solver or a cubing prodigy, this is your chance to show off those smooth moves and claim your crown as the cube champion!",
    rules: "https://docs.google.com/document/d/1EtLg2-pzT_y9ohNJJEaT_vcXU29sYKuy/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 3000, "second": 2000, "third": 1000},
    coordinators: [
      Coordinator(name: 'Priyanshu Raj', phone: '7250148414'),
      Coordinator(name: 'Sourov Debnath', phone: '9635674194'),
    ],
  ),

  //ROBOTICS

  Event(
    id: "robo1",
    category: "robotics",
    name: "Robo Rumble",
    image: "assets/event_poster/robo1.png",
    description: "ROBO RUMBLE brings the ultimate test of strategy, precision engineering, and battle-ready robotics! Competitors must construct wireless bots using only the specified list of components, ensuring a level playing field while pushing their creativity and technical skills to the limit. It is very beginner friendly. The event features three sub events: Bot Pursuit, where chasers hunt down runners in a timer-based shrinking arena; Tug and Tussle, a battle of torque and traction in a robo-style tug of war; and Robo Sumo, where power and positioning collide as bots attempt to push each other out of the ring. Each round tests a different aspect of the same design.",
    rules: "https://docs.google.com/document/d/13kruQPQsIUz1OeKboSeKwmBfcdwu50c0/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 200,
    gform: "https://forms.gle/zTcKx29xF11hs9wR9",
    prizePool: {"first": 15000},
    coordinators: [
      Coordinator(name: 'Pratyush', phone: '8617780658'),
    ],
  ),
  Event(
    id: "robo2",
    category: "robotics",
    name: "Aerocraft",
    image: "assets/event_poster/robo2.png",
    description: "Get ready for an electrifying clash of cushion-riding titans! INSTRUO presents a high-octane battle where engineering prowess meets sheer competitive force. In this intense arena rumble, two custom-built hovercraft bots will face off with one singular, aggressive objective: to push the opponent's machine right out of the ring! Only the bot that satisfies every crucial design and technical specification detailed in the rulebook, and is verified by the Robodarshan Team. This isn't just a demolition derby—it's a calculated, point-based war of attrition! Over an adrenaline-pumping 3-minute match duration, teams will fight to score maximum points and secure their path to the next round. But beware: in the event of a tie, the team that demonstrates superior control and finesse over their machine will snatch the crucial tie-breaker point. Remember this: the arena is sacred, the rules are set, and in any moment of contention, the decision of Team Robodarshan is final and binding. Prepare your crafts, strategize your moves, and may the best bot hover its way to victory!",
    rules: "https://docs.google.com/document/d/1NKsK3jZZVczsOItYCaYoeP7h5dLb_0Kg/edit?usp=sharing&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 3,
    maxTeamSize: 4,
    fee: 200,
    gform: "https://forms.gle/qPKLiRdoGAitN4sd8",
    prizePool: {"first": 10000},
    coordinators: [
      Coordinator(name: 'Mandeep', phone: '9021500267'),
    ],
  ),
  Event(
    id: "robo3",
    category: "robotics",
    name: "Robo Soccer",
    image: "assets/event_poster/robo3.png",
    description: "RoboSoccer – When Machines Take the Field! \nGet ready for the ultimate clash of metal and motion! RoboSoccer, one of the most thrilling events of Instruo, brings innovation, precision, and strategy onto the field. Build your own bots, gear them up, and watch them battle it out in an electrifying game of soccer — where every move counts, and every goal is a test of your engineering prowess. Do you have what it takes to design the bot that dominates the arena? Whether you’re a robotics enthusiast, a strategist, or just love the adrenaline of competition, RoboSoccer is your stage to shine. \nShow your skills. Score your goals. Rule the arena.",
    rules: "https://docs.google.com/document/d/1dTbqEzssbvC-ydBqNfVBi23hpHbUgh1q/edit?usp=sharing&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 300,
    prizePool: {"first": 10000},
    gform: "https://forms.gle/As4nn894VPZe3A427",
    coordinators: [
      Coordinator(name: 'Swayam Gupta', phone: '7985873384'),
      Coordinator(name: 'Sumit Kumar', phone: '8294450614'),
    ],
  ),
  Event(
    id: "robo4",
    category: "robotics",
    name: "Death Race",
    image: "assets/event_poster/robo4.png",
    description: "Get Ready for the Ultimate Race against Time at INSTRUO Can you beat the clock? Move your engineered robots through an ultimate obstacle course as the time runs out with each tick-tock. Use your engineering and maneuvering skills to get past the finish line before the competition does. Whether you’re navigating tricky turns or overcoming challenging terrains, it’s all about staying cool under pressure and pushing your robot to the limit! Will your robot rise to the challenge and claim victory? Don’t miss this adrenaline-pumping spectacle of innovation and skill!",
    rules: "https://docs.google.com/document/d/1junjcJ94YOgqYfjDBDKgMLQ--oJKOVD4/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 2,
    maxTeamSize: 4,
    fee: 200,
    gform: "https://forms.gle/zTcKx29xF11hs9wR9",
    prizePool: {"first": 15000},
    coordinators: [
      Coordinator(name: 'Pinak Parate', phone: '9689311358'),
    ],
  ),
  Event(
    id: "robo5",
    category: "robotics",
    name: "Robo Wars",
    image: "assets/event_poster/robo5.png",
    description: "Where metal meets mayhem, and engineering becomes entertainment. Get ready to witness the ultimate clash of innovation and destruction at ROBOWARS, the adrenaline-fueled centerpiece of INSTRUO! This is not just a battle—it's a test of engineering prowess, strategic control, and weaponized creativity. Teams will design and construct remote-controlled combat robots to face off in a high-voltage tournament where only the strongest survive.",
    rules: "https://docs.google.com/document/d/1AqDN99ZCPrr30H0fVGuQ9Dsm0V7qXlb8/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 4,
    maxTeamSize: 5,
    fee: 1000,
    iiestFee: 150,
    gform: "https://forms.gle/Ser8R2L1ZYZfnN4X6",
    prizePool: {"first": 100000},
    coordinators: [
      Coordinator(name: 'Pratyush & Mandeep', phone: '8617780658'),
    ],
  ),

  // GAMING

  Event(
    id: "game1",
    category: "gaming",
    name: "Fifa",
    image: "assets/event_poster/game1.png",
    description: "The FIFA Showdown is a competitive 1v1 knockout-style gaming tournament conducted as part of the INSTRUO. The event aims to engage participants in a high-energy, skill-based competition centered around the popular football simulation game FIFA  It provides a platform for gamers to showcase their reflexes, strategic thinking, and in-game decision-making under pressure. The tournament will follow a single-elimination format, where players face off in head-to-head matches until a winner emerges. Emphasis will be placed on fair play, sportsmanship, and maintaining a competitive but enjoyable atmosphere throughout the event.",
    rules: "https://docs.google.com/document/d/1-qzzjgtN2DQcWToSOwkbh_DZtyeDUF5D/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Pritam', phone: '7865009382'),
    ],
  ),
  Event(
    id: "game2",
    category: "gaming",
    name: "BGMI",
    image: "assets/event_poster/game2.jpeg",
    description: "Gear up, gamers! It’s time to drop into the ultimate BGMI showdown at INSTRUO — where fun meets fierce competition! Squad up with your buddies, plan your drops, and outsmart your opponents as you chase that sweet Chicken Dinner. Whether you’re the sneaky sniper, the fearless rusher, or the all-round team player, every move counts! Bring your best game, some good vibes, and maybe a little luck — because in this battleground, anything can happen! So grab your squad, load up, and let’s see who becomes the last one standing!",
    rules: "https://docs.google.com/document/d/10XUSGMBRTRqZmFI0AtN5u2hVTMoDaljY/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 4,
    maxTeamSize: 4,
    fee: 200,
    gform: "",
    prizePool: {"first": 10000},
    coordinators: [
      Coordinator(name: 'Bikarm Kumar', phone: '6203294110'),
    ],
  ),
  Event(
    id: "game3",
    category: "gaming",
    name: "Valorant",
    image: "assets/event_poster/game3.png",
    description: "Get ready, Agents! Valorant is dropping into Instruo with non-stop action, insane clutches, and next-level plays. This is where squads rise, legends are born, and every headshot counts. Bring your best aim, sharpest strats, and unstoppable energy, because only the bold will claim glory. Lock in, load up, and let the showdown begin! Adrenaline-pumping 5v5 action. A stage where skill meets teamwork Mind-bending plays, insane clutches, and unforgettable highlights. Glory, bragging rights, and exciting prizes are up for grabs. So rally your squad, sharpen your reflexes, and step into the arena where every click counts and every second matters. The only question is “Will you be the last Agent standing?” Instruo x Valorant: Where legends are made, one round at a time.",
    rules: "https://docs.google.com/document/d/1nNNxDWDL2Cq7uy5ebne23UwYlIDes09P/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 5,
    maxTeamSize: 5,
    fee: 200,
    gform: "https://docs.google.com/forms/d/e/1FAIpQLScCN7wInImqeegsIw0WkgCDZBFyh99_cy7OfPXCWfAwkOe6NA/viewform?usp=header",
    prizePool: {"first": 4000, "second": 2500, "third": 1500},
    coordinators: [
      Coordinator(name: 'Debjit Maity', phone: '8167025227'),
    ],
  ),
 
  Event(
    id: "game4",
    category: "gaming",
    name: "King's Conquest",
  image: "assets/event_poster/game4.png",
    description: "Are you ready for electrifying battle of wits where one wrong move can make or break you. We bring to you King’s Conquest a round-robin over the board rapid chess tournament that will allow to test your wits against the best. Only the strong shall prevail and the weak shall perish. So are you ready to crown yourself the next King of the 64 Squares?",
    rules: "https://docs.google.com/document/d/1R5Bl3HyRab9LvWtLVpMnppfXs7lzwARp/edit?usp=drive_link&ouid=118260888776444936740&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    iiestFee: 30,
    fee: 50,
    gform: "",
  prizePool: {"first": 2000, "second": 1500, "third": 1000, "fourth": 800, "fifth": 700, "sixth": 600, "seventh": 500, "eighth": 400, "ninth": 300, "tenth": 200},
    coordinators: [
      Coordinator(name: 'Anjishnu Gupta', phone: '8768453342'),
    ],
  ),
   Event(
    id: "game5",
    category: "gaming",
    name: "Real Cricket",
    image: "assets/event_poster/game5.jpeg",
    description: "Gear up, champs! It’s time to swap the field for your phone and dive into Real Cricket, the ultimate mobile cricket clash where timing, tactics, and precision decide your fate! Step onto the virtual pitch, build your dream innings, and smash those sixes like a pro — because every shot counts and every over brings you closer to victory! Whether you’re a cover drive king or a yorker specialist, this is your stage to show off your cricketing instincts and dominate the leaderboard. So pad up, grab your virtual bat, and let’s see who hits it out of the park!",
    rules: "https://docs.google.com/document/d/13glQjLBMniFD7ELwy8cu4nEo8TEcXYFk/edit?usp=drive_link&ouid=116690350005654047734&rtpof=true&sd=true",
    minTeamSize: 1,
    maxTeamSize: 1,
    fee: 200,
    gform: "",
    prizePool: {"first": 10000},
    coordinators: [
      Coordinator(name: 'Bikarm Kumar', phone: '6203294110'),
    ],
  ),
];

