import 'events_model.dart';

final List<Event> events = [
  Event(
    id: "tech1",
    category: "technical",
    name: "Cad Catalyst",
    image: "assets/fest.png",
    description: "Unleash your creativity and your skills in our cutting-edge CAD competition. Design innovative 3D models using advanced computer-aided design software whether it's engineering marvels or futuristic concepts. Think it and design it!",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech2",
    category: "technical",
    name: "Rise Above",
    image: "assets/fest.png",
    description: "Enter the aerodynamic arena of design, build, and flight. Craft radio-controlled aircraft that lift smoothly, fly stably, and carry a payload aloft for at least 30 seconds. A high-flying test of creativity, aerodynamics, and hands-on engineering.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech3",
    category: "technical",
    name: "Wired In",
    image: "assets/fest.png",
    description: "Compete in a one-on-one soccer match with your team’s manually controlled robot. Showcase your technical skills and strategic thinking as your robots strive to score exhilarating goals on the field.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech4",
    category: "technical",
    name: "Doped",
    image: "assets/fest.png",
    description: "A stimulating quiz competition organized by the Department of Electronics and Telecommunication Engineering to tackle challenging rounds that will test your intellect in the ever-evolving landscape of electronics",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech5",
    category: "technical",
    name: "Ode to Code",
    image: "assets/fest.png",
    description: "A coding showdown designed to push you to your limits. Solve algorithmic puzzles under pressure, optimize every line, and outsmart the clock. Ode2Code is where coders prove their mettle in logic and problem-solving.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech6",
    category: "technical",
    name: "EO Fool",
    image: "assets/fest.png",
    description: "Enter the digital battlefield of puzzles, exploits, and codes. From cryptography to reverse engineering, each hidden flag tests your persistence and skill. A 48-hour war of wit, strategy, and pure hacking spirit.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech7",
    category: "technical",
    name: "Hydroblast",
    image: "assets/fest.png",
    description: "Unleash your coding mastery in the ultimate competition, tackling real-world challenges. Compete against top talent, take on the challenge, and code your way to victory for exciting prizes!",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech8",
    category: "technical",
    name: "Minequest",
    image: "assets/fest.png",
    description: "An exciting quiz competition testing knowledge of mining, mineral processing, and the energy sector. Participants will engage in thrilling rounds, challenging their understanding of industry innovatiminequest",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "robo1",
    category: "robotics",
    name: "Robo Soccer",
    image: "assets/fest.png",
    description: "Compete in a one-on-one soccer match with your team’s manually controlled robot. Showcase your technical skills and strategic thinking as your robots strive to score exhilarating goals on the field. ",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "robo2",
    category: "robotics",
    name: "Robowars (15kg)",
    image: "assets/fest.png",
    description: "Experience a battle of aggression, control, and style as robots go head-to-head in armed and deadly combat, with warriors dueling for honor and loyalty in an arena of destruction.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "robo3",
    category: "robotics",
    name: "Death Race",
    image: "assets/fest.png",
    description: "Witness the thrill as robots navigate through challenging terrains and obstacle courses to reach the finish line in the shortest time possible.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "robo4",
    category: "robotics",
    name: "Robo Rumble",
    image: "assets/fest.png",
    description: "Get ready to witness the clash of gears and wits at Robo Rumble, a premier robotics event that will push the boundaries of design, strategy, and pure engineering power. Our competition is a true test of a robot's versatility, challenging teams across three distinct and high-stakes events.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "game1",
    category: "gaming",
    name: "Bgmi",
    image: "assets/fest.png",
    description: "jump into the battlefield,assemble your squad, and put your skills to the test as you compete against the best for a chance to win exciting prizes!",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "game2",
    category: "gaming",
    name: "Fifa",
    image: "assets/fest.png",
    description: "Calling all gamers and football fantasies!get ready for an exciting Fifa gaming showdown where you can show off your skills,outplay your opponents,and claim the ultimate victory!",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "game3",
    category: "gaming",
    name: "Valorant",
    image: "assets/fest.png",
    description: "Get ready to lock in your agents and showcase your skills as in the ultimate Valorant Tournament! Assemble your squad, strategize every move, and battle it out in intense matches where precision, teamwork, and clutch moments decide the champions. Glory, bragging rights, and exciting rewards await—are you ready to claim the title?",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "game4",
    category: "gaming",
    name: "Chess",
    image: "assets/fest.png",
    description: "Step into the world of strategy and intellect as the Chess Tournament begins. Compete against brilliant minds, showcase your skill, and make every move count in this ultimate battle of wits and patience. From opening gambits to final checkmates, the board becomes the arena where champions are made.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen1",
    category: "general",
    name: "Mayday Mystery",
    image: "assets/fest.png",
    description: "Brought by SCAGE, A thrilling scavenger hunt where logic meets adventure. Decode mind-bending riddles, chase clues across the campus, and unlock hidden treasures with your team. Wit, speed, and collaboration will decide who emerges victorious.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen2",
    category: "general",
    name: "Vicharagni",
    image: "assets/fest.png",
    description: "Instruo’s signature debate extravaganza, blending Oxford and Parliamentary formats. From technology to ethics, this stage is set for fiery exchanges of ideas. Where intellect ignites and perspectives collide, Vicharagni celebrates the true power of discourse.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen3",
    category: "general",
    name: "Founders Goal",
    image: "assets/fest.png",
    description: "The quintessential platform to pitch your groundbreaking business concepts and visionary solutions. Compete alongside fellow entrepreneurs, and mesmerize a panel of seasoned investors and industry experts.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen4",
    category: "general",
    name: "Doped",
    image: "assets/fest.png",
    description: "Fast, fun, and fierce — Battle of Bards is a clash of wits where words, puzzles, and quick thinking rule the stage. Be spontaneous, be sharp, and let your creativity shine in this high-energy wordplay arena.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen5",
    category: "general",
    name: "Ignite",
    image: "assets/fest.png",
    description: "Curated by ichhe, a dynamic essay and presentation pitch competition to challenge participants to devise innovative ideas for enhancing education for underprivileged children.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen6",
    category: "general",
    name: "War of Titans",
    image: "assets/fest.png",
    description: "A captivating competition to test participants' analytical skills, challenging them to think critically, solve problems, and make data-driven decisions, while competing with individuals from diverse academic and professional backgrounds.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen7",
    category: "general",
    name: "Chitrakatha",
    image: "assets/fest.png",
    description: "brought by catharsis. Bring together a series of photos that capture emotions, ideas, or events — and let your lens weave a powerful narrative. Whether it’s friendship, campus life, traditions, or a message for society, your pictures will do the talking",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen8",
    category: "general",
    name: "Narrimate",
    image: "assets/fest.png",
    description: "unleash your imagination in the age of AI! Narrimate challenges you to script, design, and animate your own short story using AI or any creative tool of your choice. A battle of originality, vision, and storytelling like never before.",
    maxTeamSize: 4,
    fee: 100,
  ),
];

