import '../events_model.dart';

final List<Event> generalEvents = [
  Event(
    id: "gen1",
    category: "general",
    name: "Mayday Mystery",
    image: "assets/fest.png",
    description: "Brought by SCAGE, A thrilling scavenger hunt where logic meets adventure. Decode mind-bending riddles, chase clues across the campus, and unlock hidden treasures with your team. Wit, speed, and collaboration will decide who emerges victorious.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen2",
    category: "general",
    name: "Vicharagni",
    image: "assets/fest.png",
    description: "Instruo’s signature debate extravaganza, blending Oxford and Parliamentary formats. From technology to ethics, this stage is set for fiery exchanges of ideas. Where intellect ignites and perspectives collide, Vicharagni celebrates the true power of discourse.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen3",
    category: "general",
    name: "Founders Goal",
    image: "assets/fest.png",
    description: "The quintessential platform to pitch your groundbreaking business concepts and visionary solutions. Compete alongside fellow entrepreneurs, and mesmerize a panel of seasoned investors and industry experts.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen4",
    category: "general",
    name: "Doped",
    image: "assets/fest.png",
    description: "Fast, fun, and fierce — Battle of Bards is a clash of wits where words, puzzles, and quick thinking rule the stage. Be spontaneous, be sharp, and let your creativity shine in this high-energy wordplay arena.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen5",
    category: "general",
    name: "Ignite",
    image: "assets/fest.png",
    description: "Curated by ichhe, a dynamic essay and presentation pitch competition to challenge participants to devise innovative ideas for enhancing education for underprivileged children.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "gen6",
    category: "general",
    name: "War of Titans",
    image: "assets/fest.png",
    description: "A captivating competition to test participants' analytical skills, challenging them to think critically, solve problems, and make data-driven decisions, while competing with individuals from diverse academic and professional backgrounds.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen7",
    category: "general",
    name: "Chitrakatha",
    image: "assets/fest.png",
    description: "brought by catharsis. Bring together a series of photos that capture emotions, ideas, or events — and let your lens weave a powerful narrative. Whether it’s friendship, campus life, traditions, or a message for society, your pictures will do the talking",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "gen8",
    category: "general",
    name: "Narrimate",
    image: "assets/fest.png",
    description: "unleash your imagination in the age of AI! Narrimate challenges you to script, design, and animate your own short story using AI or any creative tool of your choice. A battle of originality, vision, and storytelling like never before.",
    maxTeamSize: 4,
    fee: 100,
  ),
];

