import '../events_model.dart';

final List<Event> technicalEvents = [
  Event(
    id: "tech1",
    category: "technical",
    name: "Cad Catalyst",
    image: "assets/fest.png",
    description: "Unleash your creativity and your skills in our cutting-edge CAD competition. Design innovative 3D models using advanced computer-aided design software whether it's engineering marvels or futuristic concepts. Think it and design it!",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech2",
    category: "technical",
    name: "Rise Above",
    image: "assets/fest.png",
    description: "Enter the aerodynamic arena of design, build, and flight. Craft radio-controlled aircraft that lift smoothly, fly stably, and carry a payload aloft for at least 30 seconds. A high-flying test of creativity, aerodynamics, and hands-on engineering.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech3",
    category: "technical",
    name: "Wired In",
    image: "assets/fest.png",
    description: "Compete in a one-on-one soccer match with your team’s manually controlled robot. Showcase your technical skills and strategic thinking as your robots strive to score exhilarating goals on the field.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech4",
    category: "technical",
    name: "Doped",
    image: "assets/fest.png",
    description: "A stimulating quiz competition organized by the Department of Electronics and Telecommunication Engineering to tackle challenging rounds that will test your intellect in the ever-evolving landscape of electronics",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech5",
    category: "technical",
    name: "Ode to Code",
    image: "assets/fest.png",
    description: "A coding showdown designed to push you to your limits. Solve algorithmic puzzles under pressure, optimize every line, and outsmart the clock. Ode2Code is where coders prove their mettle in logic and problem-solving.",
    maxTeamSize: 1,
    fee: 100,
  ),
  Event(
    id: "tech6",
    category: "technical",
    name: "EO Fool",
    image: "assets/fest.png",
    description: "Enter the digital battlefield of puzzles, exploits, and codes. From cryptography to reverse engineering, each hidden flag tests your persistence and skill. A 48-hour war of wit, strategy, and pure hacking spirit.",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech7",
    category: "technical",
    name: "Hydroblast",
    image: "assets/fest.png",
    description: "Unleash your coding mastery in the ultimate competition, tackling real-world challenges. Compete against top talent, take on the challenge, and code your way to victory for exciting prizes!",
    maxTeamSize: 4,
    fee: 100,
  ),
  Event(
    id: "tech8",
    category: "technical",
    name: "Minequest",
    image: "assets/fest.png",
    description: "An exciting quiz competition testing knowledge of mining, mineral processing, and the energy sector. Participants will engage in thrilling rounds, challenging their understanding of industry innovatiminequest",
    maxTeamSize: 4,
    fee: 100,
  ),
];

